---
title: "H4"
author: "grienne"
date: "October 12, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Foundation}
library(readxl)
library(ggplot2)
library(dplyr)
library(ResourceSelection)

dat <- read_excel("oct_11_2018_h4_table_7_18.xlsx")

dat_try <- read_excel("dat_comp.xlsx")

names(dat) <- c('wais', 'symptom')

```

```{Question 1}

Question 1

A. For the simple logistic model πi = eβi/(1 + eβi), show that if there is no diﬀerence between the exposed (b1)
    and not exposed groups (b2) (i.e., β1 = β2), then φ = 1
      
       
    
          Set φ = 1 = [ π1/ (1 − π2) ] / [ π2 (1 − π1) ] =>
                
                Cross Multiply   
                   [ π1/ (1 − π2) ] = [ π2 (1 − π1) ]
                  Multiply Out
                    π1 − π1π2 = π2 − π1π2
                    Algebra
                        π1 = π2
                      Express
                        eβ1/(1 + eβ1) =  eβ2/(1 + eβ2)
                        Cross Multiply
                          eβ1*(1 + eβ2) =  eβ2*(1 + eβ1)
                          Multiply Out 
                            eβ1 + eβ1eβ2) =  eβ2 + eβ1eβ2
                            Algebra
                              eβ1 = eβ2
                              Log
                                β1 = β2 if and only if β1 = β2
                          
                          
                  #[eβ1/(1 + eβ1) /  [1 - eβ2/(1 + eβ2) ]       /        [eβ2/(1 + eβ2) /  [1 - eβ1/(1 + eβ1) ] =>
                   #1 = { [eβ1/(1 + eβ1) * [1 - eβ2/(1 + eβ2) ]^-1       /        [eβ2/(1 + eβ2) * [1 - eβ1/(1 + eβ1) ] ^ -1 } =>
                    #  [eβ1/(1 + eβ1) * [1 - eβ2/(1 + eβ2) ]^-1 = -[eβ2/(1 + eβ2) * [1 - eβ1/(1 + eβ1) ] ^ -1 => Log & Algebra
                     #   Log eβ2/(1 + eβ1) = Log eβ1/(1 + eβ2) => exp
                      #    exp(β2)/ exp(β1) = exp (β1) / ex(β2) = 1 tf β1 - β2 = 0 => exp (β1 - β2) = 1
                       #     φ = exp(β1 - β2) = 1 if and only if β1 = β2
            
      
B. Consider J 2 × 2 tables like Table 7.13, one for each level xj of a factor, such as age group, with j = 1,...,J. 
    For the logistic model
      πij = exp(αi + βixj) / 1 + exp(αi + βixj), i = 1,2, j = 1,...,J.
        Show that log φ is constant over all tables if β1 = β2   

              if φ = exp(π1 - π2)
                then   log φ = (alpha1 - alpha2) + xj(β1 - β2) if β1 = β2
        
                    φ = O1/ O2 = π1(1−π2) / π2(1−π1)
        
```

```{r Question 2}
#This problem models section 7.8 in our text. Use the WAIS dataset (Table 7.8) and conduct logisitic regression
#of symptoms present on score. Show all your work, ideally, through embedded code and interpreted results.

q2_lr <- glm(symptom ~ wais, data = dat, family = binomial(link = "logit"))
summary(q2_lr)
exp(confint(q2_lr))
dat$fit_prop   <- fitted(q2_lr)

#(d) Replicate the plot in Figure 7.5.

#Counts by Symptom
dat_gp_2 <- dat %>%
    group_by(symptom, wais, fit_prop)  %>%
     summarise(counts= n())

#Counts by grp
dat_fin <- dat_gp_2 %>%
  group_by(wais) %>%
    mutate(n = sum(counts))

dat_comp <- dat_fin %>% 
               group_by(wais)%>% 
                  mutate(prp_count = counts / n)

write.csv(dat_comp, "dat_comp.csv")


detach("package:MASS", unload=TRUE)

#dat_fin_2 <- dat_comp %>%
 #             filter(symptom == "0") %>%
  #               select(wais, fit_prop, counts,n, prp_count)

#dat_fin_3 <- dat_comp %>%
 #             mutate(yes = n - counts) %>%
  #                filter(symptom == "0") %>%
   #                 select(wais, fit_prop, counts, yes, prp_count)
            
#names(dat_fin_3) <- c("WAIS", "fitted_prop", "no", "yes", "proportions")

#(a) Confirm the first 4 columns of Table 7.9. NB: the definition of “success” appears to have flip-flopped. Plan
#accordingly.

dat_try[1:4,]


#(b) Confirm the estimation of the βˆ’s and corresponding standard errors by extracting from your logistic regression
#results or explicitly calculating.

    coef(q2_lr)
    summary(q2_lr)$coefficients[, 2]

#(c) Verify the Hosmer-Lemeshow test statistic as presented in Table 7.10.

require(MASS)
q2_hl <- hoslem.test(fitted(q2_lr), dat$symptom, g=10)
q2_hl    
    
#(d) Replicate the plot in Figure 7.5.


p <- ggplot(data = dat_try, aes(x=wais, y=fit_prop))
p + geom_point() + geom_smooth(method = "glm", se = FALSE)

    
#(e) What do the results in (b) and (d) suggest regarding inference, i.e., what do you conclude? Use verbiage
#specific to the dataset used.

    #The probability of senility decreases with increased WAIS score.



```




```{ Question 3}

Git ID - grienne

```

```{Question 4}

Certificate also stored in git
Git-Link: https://github.com/grienne/bst_oct_11_2018.git

Completion Date 26-Aug-2018
Expiration Date 25-Aug-2021
Record ID 28316665
Verify at www.citiprogram.org/verify/?w493f4f53-6552-4fb1-8285-a171d8d5bba0-28316665
```